### ISSUE TITLE
Variables with annotations in the groups of "encapsulation" are not detected by SemGen for auto-mapping while merging.

### ISSUE THREAD

**Issue by Niloofar-Sh** [SemBioProcess/SemGen#329] opened 2020-07-07 21:28 UTC
While trying to merge a model (CellML format)  with the resultant of 2 previously merged models, SemGen cannot detect and suggest the same annotated variables for auto-mapping which exist in the encapsulated groups.

**Comment by maxneal** [comment] 2020-07-08 16:28
Hi Niloofar - could you provide some more details about this issue? I'm not sure I completely understand the problem. Is it that you have a 2-step merging task and variables that you need map in the second step are being hidden because of something that happens in the first step? If you could attach the models that you are using in the merge as well as the resulting model that would help,  too.

**Comment by Niloofar-Sh** [comment] 2020-07-08 21:54
Hi Max!
Yes, that's exactly the case. Here, first the "aortic_root_module" is
merged with "Ascending_aorta_module". I annotated some of the variables in
them and for instance I indicated the source/sink for a number of fluid
pressures (u & u_in). The result of the first merge (here is named "block2")
is going to be merged with another model (here is "brachiocephalic_module").
So what happens next is that the variables which were previously annotated
in the brick modules of "block2", don't pop up again as equivalent
variables with the ones in  "brachiocephalic_module" (supposedly because of
the encapsulation which has happened while merging the first two modules).
Also, it seems that  in "block2", the added sources/sinks have disappeared
from the previous annotation. Maybe I'm missing something while merging the
first two.🤔

**Comment by maxneal** [comment] 2020-07-10 00:19
I suspect SemGen didn't preserve some of the annotations correctly during the first merging step. Could you email me the files that you are trying to merge so I can reproduce the issue on my end?

**Comment by Niloofar-Sh** [comment] 2020-07-10 02:43
Yes, sure!
The 2 PNG files show how the modules are supposed to be connected (merged).
And also, "Final_merged_SemGen.cellml" is the result of all these merges.
The file was run and the results were validated.

[image: Slide5.png]
[image: Slide4.png]

**Comment by maxneal** [comment] 2020-08-20 23:00
Fixed in commit 9423279dd2ef0e824ac5239dcc2d79b407bab161.
The issue was not due to encapsulation, but rather the incorrect assignment of generic metadata IDs to CustomEnergyDifferential instances.

**Closed by maxneal** 2020-08-20 23:00 UTC
